name: lint
on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: install python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: run lint
      run: |
        pip install tox
        tox -e lint
